ovn-ic: Fix potential segmentation violation.
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x000000709f68 bp 0x7ffe8546c9b0 sp 0x7ffe8546c9b0 T0)
  0 0x709f68 in hmap_insert_fast ./ovs/./include/openvswitch/hmap.h
  1 0x702611 in hmap_insert_at ./ovs/./include/openvswitch/hmap.h:307:5
  2 0x70444c in ovsdb_idl_txn_write__ ./ovs/lib/ovsdb-idl.c:3631:9
  3 0x704141 in ovsdb_idl_txn_write ./ovs/lib/ovsdb-idl.c:3688:5
  4 0x6c1cd1 in icsbrec_availability_zone_set_name ./lib/ovn-ic-sb-idl.c:395:5
  5 0x5a7f1e in az_run ./ic/ovn-ic.c:144:17
  6 0x5a7f1e in main ./ic/ovn-ic.c:2323:62
  7 0x7fc605b6db74 in __libc_start_main (/lib64/libc.so.6+0x27b74)
  8 0x4c8fed in _start (/root/master-ovn/ic/ovn-ic+0x4c8fed)

Fixes: 37fd1dd378ea ("ovn-ic: Handle NB:name updates properly.")

Signed-off-by: Xavier Simonart <xsimonar@redhat.com>